name: 'RSpec action'
description: 'Run RSpec tests'
inputs:
  rubygems_api_key:
    description: 'RubyGems API key'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v1
    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{ inputs.rubygems_api_key }}"
      shell: bash
